# Constants
WIDTH, HEIGHT = 1200, 800
FPS = 60
PADDLE_WIDTH, PADDLE_HEIGHT = 330, 35
PADDLE_SPEED = 15
BALL_RADIUS = 20
EASY_BALL_SPEED = 4
HARD_BALL_SPEED = 8
BLOCK_WIDTH, BLOCK_HEIGHT = 100, 50
EASY_BLOCK_ROWS, EASY_BLOCK_COLS = 3, 10
HARD_BLOCK_ROWS, HARD_BLOCK_COLS = 5, 12
SCORE_FILE = 'scores.txt'
IMG_PATH = '1.jpg'
