name: Python CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest and generate HTML report
      run: |
        pytest --html=report.html

    - name: Run Flake8 and generate HTML report
      run: |
        flake8 --format=html --htmldir=flake8_report

    - name: Upload Pytest HTML report
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: report.html

    - name: Upload Flake8 HTML report
      uses: actions/upload-artifact@v3
      with:
        name: flake8-report
        path: flake8_report